### ISSUE TITLE
Orange Pi 5B support?

### ISSUE THREAD

**Issue by phaitonican** [ryan4yin/nixos-rk3588#11]
Orange Pi 5B support soon pls? there is another repo for it but it would be better when its here for more support

**Comment by ryan4yin** [comment]
@phaitonican I don't have a orangepi 5b, so it's troublesome for me to test the code, and I don't have time recently.

So I suggest you use the 'another repo' you mentioned directly: [fb87/nixos-orangepi-5x](https://github.com/fb87/nixos-orangepi-5x).

**Comment by phaitonican** [comment]
Sorry thanks very much for your help still!

**Comment by ryan4yin** [comment]
Planning to support Orange Pi 5B, if you are willing to help with the test, please let me know.

**Comment by phaitonican** [comment]
Hello. Yes I can test no Problem.

I opened PR, it got working config and file system table.

Only thing I couldn't do was compile u-boot into image file. Orange Pi 5b has no SPI flash, u-boot has to be inside image.

**Comment by ryan4yin** [comment]
Yeah I see it, https://github.com/ryan4yin/nixos-rk3588/pull/13, I‘ll integrate Si Dao's work into this project.

BTW, as Orange PI 5B is very similar to Orange Pi 5, I wonder if 5B can also be booted from UEFI([edk2-rk3588](https://github.com/edk2-porting/edk2-rk3588)), which will be much more flexible than U-Boot. Related docs: https://github.com/ryan4yin/nixos-rk3588/blob/main/UEFI.md
