### ISSUE TITLE
Error download mali_csffw.bin

### ISSUE THREAD

**Issue by webhive** [ryan4yin/nixos-rk3588#36]
Getting the following error wile trying to build image with this command

`nix build github:ryan4yin/nixos-rk3588/2024032400#sdImage-opi5plus-cross`

```console
 last 7 log lines:
 >
 > trying https://github.com/JeffyCN/rockchip_mirrors/raw/309268f7a34ca0bba0ab94a0b09feb0191c77fb8/firmware/g610/mali_csffw.bin
 >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
 >                                  Dload  Upload   Total   Spent    Left  Speed
 >   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 > curl: (22) The requested URL returned error: 404
 > error: cannot download mali_csffw.bin from any mirror
 For full logs, run 'nix log /nix/store/h7d0jsc6bc71qqz267g8nlzskqi0znm7-mali_csffw.bin.drv'.
```

So there is no such file on provided link

**Comment by webhive** [comment]
Found this file here https://github.com/JeffyCN/mirrors/raw/libmali/firmware/g610/mali_csffw.bin

**Comment by HeroBrine1st** [comment]
Try to build latest available revision. I have submitted a PR https://github.com/ryan4yin/nixos-rk3588/pull/35 earlier with updates to that package. I did not target this issue (URL was still alive then), but that PR fixes it too.
