### ISSUE TITLE
Documentation: UEFI.md and U-boot.md need to be updated

### ISSUE THREAD

**Issue by cessationoftime** [ryan4yin/nixos-rk3588#41]
The nix build commands now fail because of the mali firmware:
```
nix build github:ryan4yin/nixos-rk3588/2024032400#rawEfiImage-opi5plus --show-trace -L --verbose
```

changing to point at the main branch succeeds:

```
nix build github:ryan4yin/nixos-rk3588/main#rawEfiImage-opi5plus --show-trace -L --verbose
```

A new tag and an update to the commands in these documents is needed.

**Comment by ryan4yin** [comment]
Fixed by https://github.com/ryan4yin/nixos-rk3588/commit/b8d0c197baf776944c748ff3c3d81814c1f3bf58
