### ISSUE TITLE
So... How does one actually install NixOS on the emmc?

### ISSUE THREAD

**Issue by zilti** [ryan4yin/nixos-rk3588#50]
That is a glaring omission in the documentation. It says "just follow the official NixOS documentation", but by doing that, you end up with an unbootable system (stuck at "EFI stub: Exiting boot services...").

**Comment by ryan4yin** [comment]
That's a mistake, I'll fix that.

**Comment by zilti** [comment]
I was thinking about just `dd`ing the rawEfi image onto the emmc, but that won't make much sense since it lacks a configuration.nix file to build off of.

**Comment by ryan4yin** [comment]
> I was thinking about just `dd`ing the rawEfi image onto the emmc, but that won't make much sense since it lacks a configuration.nix file to build off of.

`dd` is indeed an option, you can generate your hardware-configuration.nix by `nixos-generate-config` after `dd`-ing.
The main drawback of `dd` is that, you cannot customize the disk format & filesystem.
