### ISSUE TITLE
Turing RK1 support

### ISSUE THREAD

**Issue by carina-akaia** [ryan4yin/nixos-rk3588#54]
I have one [Turing RK1](https://docs.turingpi.com/docs/turing-rk1-specs-and-io-ports) 32Gb up and running on Ubuntu 24.04 as a daily driver at the moment, but I'd like to have NixOS instead and I can assist with testing

**Comment by ryan4yin** [comment]
My recent focus has not been on this project. If you need it, I suggest you try adding support for Turing RK1 to this project yourself. #40 is a good example.
