### ISSUE TITLE
Minimal configuration.nix of flakes.nix that just works

### ISSUE THREAD

**Issue by gnull** [ryan4yin/nixos-rk3588#57]
Hi!

Is it possible to make a minimal configuration.nix (or flake.nix) that one can copy to [step 3](https://github.com/ryan4yin/nixos-rk3588/blob/main/UEFI.md#user-content-3-install-nixos-into-ssd--emmc-via-nixos-install) (after doing nixos-generate-config) to get the device running? I'm running Orange Pi 5 Plus.

I tried looking at this repo and couldn't really understand what I need to add to the result of nixos-generate-config to get the board running. I don't know what is colmena and would just like to use Nix with `nixos-rebuild switch` in the device. I'm guessing there may be more users like me.

Ivan

**Comment by HeroBrine1st** [comment]
I don't exactly know how to create a configuration.nix standalone, but I can propose you to see my early flake (but for base opi5): https://github.com/HeroBrine1st/flake/tree/a6d5bc20f31ca3ae9b2b90d17be3a1a76f57645f

Actually you only need flake.nix, everything else is the same.
