### ISSUE TITLE
nixos-anywhere?, nix-install, nix-generators

### ISSUE THREAD

**Issue by realsnick** [ryan4yin/nixos-rk3588#7]
have you thought of integrating this with nixos-anywhere, nix-install nix-generators? 

I'll be happy to help.

**Comment by ryan4yin** [comment]
Flashing a raw image into SD card / SSD directly is enough for me. What are the benefits of nix-anywhere in this scenario?

**Comment by realsnick** [comment]
just to be able to update it remotely... it is something I aam working towards to with the orange pi 5 plus. the way nixos-anywhere works it will load a new installer kernel, boot to it, then do the reinstall - that can also mean repartitions.

**Comment by ryan4yin** [comment]
As for remote deployment, I've already provide a demofor it:

https://github.com/ryan4yin/nixos-rk3588/tree/main/demo

**Comment by realsnick** [comment]
yes, i rather use the normal nixos-rebuild switch with remote endpoint or the nixos-anywhere... its ok, i'll continue on it at a fork.

**Comment by realsnick** [comment]
great work btw! and as i have it setup with debugger, let me know if you want me to tests some stuff.

**Comment by ryan4yin** [comment]
> its ok, i'll continue on it at a fork.

Or could this be another demo? Something like my colmena demo, where the changes to the original flake are minimal and that's acceptable to me.

**Comment by ryan4yin** [comment]
You can do your work on your fork first, and I'll see how much it's changed when it's done.

**Comment by realsnick** [comment]
btw, have you looked at https://github.com/orangepi-xunlong/orangepi-build/tree/next 

any plans to update to kernel 6.x?

**Comment by ryan4yin** [comment]
@realsnick I have no plans to upgrade to the latest kernel for the time being, but I will keep an eye on the progress of the upstream https://github.com/armbian/build

**Comment by realsnick** [comment]
thank you @ryan4yin if there is any guideline on updating the kernel i can pick up on it maybe early beginning of 2024

**Comment by ryan4yin** [comment]
@realsnick FYI, I've just added UEFI support for rk3588, it should supports `nixos-anywhere`, `nixos-install` & `nixos-generators` seamlessly! looking for any tests & feedback.

https://github.com/ryan4yin/nixos-rk3588/blob/main/UEFI.md

**Comment by realsnick** [comment]
sweet! will check it out!!!
